sudo: false

cache:
  directories:
  - $HOME/.stack

before_install:
- mkdir -p $HOME/.local/bin
- export PATH $HOME/.local/bin:$PATH
- travis-retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcargs --strip-components=1 -C $HOME/.local/bin '*/stack'

script:
  - stack test
